version: '3'

services:
  #--Database--#
  dbpostgres:
    container_name: dbpostgres
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=fctest
      - POSTGRES_USER=fcuser
      - POSTGRES_PASSWORD=supapass
    ports:
      - 5432:5432
    networks: 
      - back
  #--Back-end App--#
  serverapp:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - './configs/.env.production'
    ports:
      - 3000:3000
    command: npm run docker:start:prod
    links: 
      - dbpostgres
    depends_on: 
      - dbpostgres
    networks: 
      - back

networks: 
  back:
    driver: bridge